# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/marcus/git/basement

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/marcus/git/basement

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marcus/git/basement/CMakeFiles /Users/marcus/git/basement/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marcus/git/basement/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named gridstore

# Build rule for target.
gridstore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gridstore
.PHONY : gridstore

# fast build rule for target.
gridstore/fast:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/build
.PHONY : gridstore/fast

gridstore.o: gridstore.c.o

.PHONY : gridstore.o

# target to build an object file
gridstore.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/gridstore.c.o
.PHONY : gridstore.c.o

gridstore.i: gridstore.c.i

.PHONY : gridstore.i

# target to preprocess a source file
gridstore.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/gridstore.c.i
.PHONY : gridstore.c.i

gridstore.s: gridstore.c.s

.PHONY : gridstore.s

# target to generate assembly for a file
gridstore.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/gridstore.c.s
.PHONY : gridstore.c.s

src/async.o: src/async.c.o

.PHONY : src/async.o

# target to build an object file
src/async.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/async.c.o
.PHONY : src/async.c.o

src/async.i: src/async.c.i

.PHONY : src/async.i

# target to preprocess a source file
src/async.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/async.c.i
.PHONY : src/async.c.i

src/async.s: src/async.c.s

.PHONY : src/async.s

# target to generate assembly for a file
src/async.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/async.c.s
.PHONY : src/async.c.s

src/attr.o: src/attr.c.o

.PHONY : src/attr.o

# target to build an object file
src/attr.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/attr.c.o
.PHONY : src/attr.c.o

src/attr.i: src/attr.c.i

.PHONY : src/attr.i

# target to preprocess a source file
src/attr.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/attr.c.i
.PHONY : src/attr.c.i

src/attr.s: src/attr.c.s

.PHONY : src/attr.s

# target to generate assembly for a file
src/attr.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/attr.c.s
.PHONY : src/attr.c.s

src/conf.o: src/conf.c.o

.PHONY : src/conf.o

# target to build an object file
src/conf.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/conf.c.o
.PHONY : src/conf.c.o

src/conf.i: src/conf.c.i

.PHONY : src/conf.i

# target to preprocess a source file
src/conf.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/conf.c.i
.PHONY : src/conf.c.i

src/conf.s: src/conf.c.s

.PHONY : src/conf.s

# target to generate assembly for a file
src/conf.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/conf.c.s
.PHONY : src/conf.c.s

src/containers/dict.o: src/containers/dict.c.o

.PHONY : src/containers/dict.o

# target to build an object file
src/containers/dict.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/dict.c.o
.PHONY : src/containers/dict.c.o

src/containers/dict.i: src/containers/dict.c.i

.PHONY : src/containers/dict.i

# target to preprocess a source file
src/containers/dict.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/dict.c.i
.PHONY : src/containers/dict.c.i

src/containers/dict.s: src/containers/dict.c.s

.PHONY : src/containers/dict.s

# target to generate assembly for a file
src/containers/dict.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/dict.c.s
.PHONY : src/containers/dict.c.s

src/containers/dicts/hash_table.o: src/containers/dicts/hash_table.c.o

.PHONY : src/containers/dicts/hash_table.o

# target to build an object file
src/containers/dicts/hash_table.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/dicts/hash_table.c.o
.PHONY : src/containers/dicts/hash_table.c.o

src/containers/dicts/hash_table.i: src/containers/dicts/hash_table.c.i

.PHONY : src/containers/dicts/hash_table.i

# target to preprocess a source file
src/containers/dicts/hash_table.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/dicts/hash_table.c.i
.PHONY : src/containers/dicts/hash_table.c.i

src/containers/dicts/hash_table.s: src/containers/dicts/hash_table.c.s

.PHONY : src/containers/dicts/hash_table.s

# target to generate assembly for a file
src/containers/dicts/hash_table.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/dicts/hash_table.c.s
.PHONY : src/containers/dicts/hash_table.c.s

src/containers/freelist.o: src/containers/freelist.c.o

.PHONY : src/containers/freelist.o

# target to build an object file
src/containers/freelist.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/freelist.c.o
.PHONY : src/containers/freelist.c.o

src/containers/freelist.i: src/containers/freelist.c.i

.PHONY : src/containers/freelist.i

# target to preprocess a source file
src/containers/freelist.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/freelist.c.i
.PHONY : src/containers/freelist.c.i

src/containers/freelist.s: src/containers/freelist.c.s

.PHONY : src/containers/freelist.s

# target to generate assembly for a file
src/containers/freelist.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/freelist.c.s
.PHONY : src/containers/freelist.c.s

src/containers/hashset.o: src/containers/hashset.c.o

.PHONY : src/containers/hashset.o

# target to build an object file
src/containers/hashset.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/hashset.c.o
.PHONY : src/containers/hashset.c.o

src/containers/hashset.i: src/containers/hashset.c.i

.PHONY : src/containers/hashset.i

# target to preprocess a source file
src/containers/hashset.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/hashset.c.i
.PHONY : src/containers/hashset.c.i

src/containers/hashset.s: src/containers/hashset.c.s

.PHONY : src/containers/hashset.s

# target to generate assembly for a file
src/containers/hashset.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/hashset.c.s
.PHONY : src/containers/hashset.c.s

src/containers/list.o: src/containers/list.c.o

.PHONY : src/containers/list.o

# target to build an object file
src/containers/list.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/list.c.o
.PHONY : src/containers/list.c.o

src/containers/list.i: src/containers/list.c.i

.PHONY : src/containers/list.i

# target to preprocess a source file
src/containers/list.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/list.c.i
.PHONY : src/containers/list.c.i

src/containers/list.s: src/containers/list.c.s

.PHONY : src/containers/list.s

# target to generate assembly for a file
src/containers/list.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/list.c.s
.PHONY : src/containers/list.c.s

src/containers/vec.o: src/containers/vec.c.o

.PHONY : src/containers/vec.o

# target to build an object file
src/containers/vec.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/vec.c.o
.PHONY : src/containers/vec.c.o

src/containers/vec.i: src/containers/vec.c.i

.PHONY : src/containers/vec.i

# target to preprocess a source file
src/containers/vec.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/vec.c.i
.PHONY : src/containers/vec.c.i

src/containers/vec.s: src/containers/vec.c.s

.PHONY : src/containers/vec.s

# target to generate assembly for a file
src/containers/vec.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/containers/vec.c.s
.PHONY : src/containers/vec.c.s

src/dispatch.o: src/dispatch.c.o

.PHONY : src/dispatch.o

# target to build an object file
src/dispatch.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/dispatch.c.o
.PHONY : src/dispatch.c.o

src/dispatch.i: src/dispatch.c.i

.PHONY : src/dispatch.i

# target to preprocess a source file
src/dispatch.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/dispatch.c.i
.PHONY : src/dispatch.c.i

src/dispatch.s: src/dispatch.c.s

.PHONY : src/dispatch.s

# target to generate assembly for a file
src/dispatch.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/dispatch.c.s
.PHONY : src/dispatch.c.s

src/error.o: src/error.c.o

.PHONY : src/error.o

# target to build an object file
src/error.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/error.c.o
.PHONY : src/error.c.o

src/error.i: src/error.c.i

.PHONY : src/error.i

# target to preprocess a source file
src/error.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/error.c.i
.PHONY : src/error.c.i

src/error.s: src/error.c.s

.PHONY : src/error.s

# target to generate assembly for a file
src/error.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/error.c.s
.PHONY : src/error.c.s

src/field_type.o: src/field_type.c.o

.PHONY : src/field_type.o

# target to build an object file
src/field_type.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/field_type.c.o
.PHONY : src/field_type.c.o

src/field_type.i: src/field_type.c.i

.PHONY : src/field_type.i

# target to preprocess a source file
src/field_type.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/field_type.c.i
.PHONY : src/field_type.c.i

src/field_type.s: src/field_type.c.s

.PHONY : src/field_type.s

# target to generate assembly for a file
src/field_type.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/field_type.c.s
.PHONY : src/field_type.c.s

src/frag.o: src/frag.c.o

.PHONY : src/frag.o

# target to build an object file
src/frag.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frag.c.o
.PHONY : src/frag.c.o

src/frag.i: src/frag.c.i

.PHONY : src/frag.i

# target to preprocess a source file
src/frag.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frag.c.i
.PHONY : src/frag.c.i

src/frag.s: src/frag.c.s

.PHONY : src/frag.s

# target to generate assembly for a file
src/frag.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frag.c.s
.PHONY : src/frag.c.s

src/frag_printer.o: src/frag_printer.c.o

.PHONY : src/frag_printer.o

# target to build an object file
src/frag_printer.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frag_printer.c.o
.PHONY : src/frag_printer.c.o

src/frag_printer.i: src/frag_printer.c.i

.PHONY : src/frag_printer.i

# target to preprocess a source file
src/frag_printer.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frag_printer.c.i
.PHONY : src/frag_printer.c.i

src/frag_printer.s: src/frag_printer.c.s

.PHONY : src/frag_printer.s

# target to generate assembly for a file
src/frag_printer.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frag_printer.c.s
.PHONY : src/frag_printer.c.s

src/frag_printers/console_printer.o: src/frag_printers/console_printer.c.o

.PHONY : src/frag_printers/console_printer.o

# target to build an object file
src/frag_printers/console_printer.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frag_printers/console_printer.c.o
.PHONY : src/frag_printers/console_printer.c.o

src/frag_printers/console_printer.i: src/frag_printers/console_printer.c.i

.PHONY : src/frag_printers/console_printer.i

# target to preprocess a source file
src/frag_printers/console_printer.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frag_printers/console_printer.c.i
.PHONY : src/frag_printers/console_printer.c.i

src/frag_printers/console_printer.s: src/frag_printers/console_printer.c.s

.PHONY : src/frag_printers/console_printer.s

# target to generate assembly for a file
src/frag_printers/console_printer.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frag_printers/console_printer.c.s
.PHONY : src/frag_printers/console_printer.c.s

src/frags/frag_host_vm.o: src/frags/frag_host_vm.c.o

.PHONY : src/frags/frag_host_vm.o

# target to build an object file
src/frags/frag_host_vm.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frags/frag_host_vm.c.o
.PHONY : src/frags/frag_host_vm.c.o

src/frags/frag_host_vm.i: src/frags/frag_host_vm.c.i

.PHONY : src/frags/frag_host_vm.i

# target to preprocess a source file
src/frags/frag_host_vm.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frags/frag_host_vm.c.i
.PHONY : src/frags/frag_host_vm.c.i

src/frags/frag_host_vm.s: src/frags/frag_host_vm.c.s

.PHONY : src/frags/frag_host_vm.s

# target to generate assembly for a file
src/frags/frag_host_vm.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/frags/frag_host_vm.c.s
.PHONY : src/frags/frag_host_vm.c.s

src/global.o: src/global.c.o

.PHONY : src/global.o

# target to build an object file
src/global.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/global.c.o
.PHONY : src/global.c.o

src/global.i: src/global.c.i

.PHONY : src/global.i

# target to preprocess a source file
src/global.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/global.c.i
.PHONY : src/global.c.i

src/global.s: src/global.c.s

.PHONY : src/global.s

# target to generate assembly for a file
src/global.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/global.c.s
.PHONY : src/global.c.s

src/grid.o: src/grid.c.o

.PHONY : src/grid.o

# target to build an object file
src/grid.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/grid.c.o
.PHONY : src/grid.c.o

src/grid.i: src/grid.c.i

.PHONY : src/grid.i

# target to preprocess a source file
src/grid.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/grid.c.i
.PHONY : src/grid.c.i

src/grid.s: src/grid.c.s

.PHONY : src/grid.s

# target to generate assembly for a file
src/grid.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/grid.c.s
.PHONY : src/grid.c.s

src/grid_cursor.o: src/grid_cursor.c.o

.PHONY : src/grid_cursor.o

# target to build an object file
src/grid_cursor.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/grid_cursor.c.o
.PHONY : src/grid_cursor.c.o

src/grid_cursor.i: src/grid_cursor.c.i

.PHONY : src/grid_cursor.i

# target to preprocess a source file
src/grid_cursor.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/grid_cursor.c.i
.PHONY : src/grid_cursor.c.i

src/grid_cursor.s: src/grid_cursor.c.s

.PHONY : src/grid_cursor.s

# target to generate assembly for a file
src/grid_cursor.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/grid_cursor.c.s
.PHONY : src/grid_cursor.c.s

src/hash.o: src/hash.c.o

.PHONY : src/hash.o

# target to build an object file
src/hash.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/hash.c.o
.PHONY : src/hash.c.o

src/hash.i: src/hash.c.i

.PHONY : src/hash.i

# target to preprocess a source file
src/hash.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/hash.c.i
.PHONY : src/hash.c.i

src/hash.s: src/hash.c.s

.PHONY : src/hash.s

# target to generate assembly for a file
src/hash.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/hash.c.s
.PHONY : src/hash.c.s

src/indexes/hindex.o: src/indexes/hindex.c.o

.PHONY : src/indexes/hindex.o

# target to build an object file
src/indexes/hindex.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/hindex.c.o
.PHONY : src/indexes/hindex.c.o

src/indexes/hindex.i: src/indexes/hindex.c.i

.PHONY : src/indexes/hindex.i

# target to preprocess a source file
src/indexes/hindex.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/hindex.c.i
.PHONY : src/indexes/hindex.c.i

src/indexes/hindex.s: src/indexes/hindex.c.s

.PHONY : src/indexes/hindex.s

# target to generate assembly for a file
src/indexes/hindex.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/hindex.c.s
.PHONY : src/indexes/hindex.c.s

src/indexes/hindexes/lsearch_hindex.o: src/indexes/hindexes/lsearch_hindex.c.o

.PHONY : src/indexes/hindexes/lsearch_hindex.o

# target to build an object file
src/indexes/hindexes/lsearch_hindex.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/hindexes/lsearch_hindex.c.o
.PHONY : src/indexes/hindexes/lsearch_hindex.c.o

src/indexes/hindexes/lsearch_hindex.i: src/indexes/hindexes/lsearch_hindex.c.i

.PHONY : src/indexes/hindexes/lsearch_hindex.i

# target to preprocess a source file
src/indexes/hindexes/lsearch_hindex.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/hindexes/lsearch_hindex.c.i
.PHONY : src/indexes/hindexes/lsearch_hindex.c.i

src/indexes/hindexes/lsearch_hindex.s: src/indexes/hindexes/lsearch_hindex.c.s

.PHONY : src/indexes/hindexes/lsearch_hindex.s

# target to generate assembly for a file
src/indexes/hindexes/lsearch_hindex.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/hindexes/lsearch_hindex.c.s
.PHONY : src/indexes/hindexes/lsearch_hindex.c.s

src/indexes/vindex.o: src/indexes/vindex.c.o

.PHONY : src/indexes/vindex.o

# target to build an object file
src/indexes/vindex.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/vindex.c.o
.PHONY : src/indexes/vindex.c.o

src/indexes/vindex.i: src/indexes/vindex.c.i

.PHONY : src/indexes/vindex.i

# target to preprocess a source file
src/indexes/vindex.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/vindex.c.i
.PHONY : src/indexes/vindex.c.i

src/indexes/vindex.s: src/indexes/vindex.c.s

.PHONY : src/indexes/vindex.s

# target to generate assembly for a file
src/indexes/vindex.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/vindex.c.s
.PHONY : src/indexes/vindex.c.s

src/indexes/vindexes/hash_vindex.o: src/indexes/vindexes/hash_vindex.c.o

.PHONY : src/indexes/vindexes/hash_vindex.o

# target to build an object file
src/indexes/vindexes/hash_vindex.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/vindexes/hash_vindex.c.o
.PHONY : src/indexes/vindexes/hash_vindex.c.o

src/indexes/vindexes/hash_vindex.i: src/indexes/vindexes/hash_vindex.c.i

.PHONY : src/indexes/vindexes/hash_vindex.i

# target to preprocess a source file
src/indexes/vindexes/hash_vindex.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/vindexes/hash_vindex.c.i
.PHONY : src/indexes/vindexes/hash_vindex.c.i

src/indexes/vindexes/hash_vindex.s: src/indexes/vindexes/hash_vindex.c.s

.PHONY : src/indexes/vindexes/hash_vindex.s

# target to generate assembly for a file
src/indexes/vindexes/hash_vindex.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/indexes/vindexes/hash_vindex.c.s
.PHONY : src/indexes/vindexes/hash_vindex.c.s

src/inet/request.o: src/inet/request.c.o

.PHONY : src/inet/request.o

# target to build an object file
src/inet/request.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/inet/request.c.o
.PHONY : src/inet/request.c.o

src/inet/request.i: src/inet/request.c.i

.PHONY : src/inet/request.i

# target to preprocess a source file
src/inet/request.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/inet/request.c.i
.PHONY : src/inet/request.c.i

src/inet/request.s: src/inet/request.c.s

.PHONY : src/inet/request.s

# target to generate assembly for a file
src/inet/request.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/inet/request.c.s
.PHONY : src/inet/request.c.s

src/inet/response.o: src/inet/response.c.o

.PHONY : src/inet/response.o

# target to build an object file
src/inet/response.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/inet/response.c.o
.PHONY : src/inet/response.c.o

src/inet/response.i: src/inet/response.c.i

.PHONY : src/inet/response.i

# target to preprocess a source file
src/inet/response.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/inet/response.c.i
.PHONY : src/inet/response.c.i

src/inet/response.s: src/inet/response.c.s

.PHONY : src/inet/response.s

# target to generate assembly for a file
src/inet/response.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/inet/response.c.s
.PHONY : src/inet/response.c.s

src/inet/server.o: src/inet/server.c.o

.PHONY : src/inet/server.o

# target to build an object file
src/inet/server.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/inet/server.c.o
.PHONY : src/inet/server.c.o

src/inet/server.i: src/inet/server.c.i

.PHONY : src/inet/server.i

# target to preprocess a source file
src/inet/server.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/inet/server.c.i
.PHONY : src/inet/server.c.i

src/inet/server.s: src/inet/server.c.s

.PHONY : src/inet/server.s

# target to generate assembly for a file
src/inet/server.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/inet/server.c.s
.PHONY : src/inet/server.c.s

src/interval.o: src/interval.c.o

.PHONY : src/interval.o

# target to build an object file
src/interval.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/interval.c.o
.PHONY : src/interval.c.o

src/interval.i: src/interval.c.i

.PHONY : src/interval.i

# target to preprocess a source file
src/interval.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/interval.c.i
.PHONY : src/interval.c.i

src/interval.s: src/interval.c.s

.PHONY : src/interval.s

# target to generate assembly for a file
src/interval.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/interval.c.s
.PHONY : src/interval.c.s

src/mondrian.o: src/mondrian.c.o

.PHONY : src/mondrian.o

# target to build an object file
src/mondrian.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/mondrian.c.o
.PHONY : src/mondrian.c.o

src/mondrian.i: src/mondrian.c.i

.PHONY : src/mondrian.i

# target to preprocess a source file
src/mondrian.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/mondrian.c.i
.PHONY : src/mondrian.c.i

src/mondrian.s: src/mondrian.c.s

.PHONY : src/mondrian.s

# target to generate assembly for a file
src/mondrian.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/mondrian.c.s
.PHONY : src/mondrian.c.s

src/mvm.o: src/mvm.c.o

.PHONY : src/mvm.o

# target to build an object file
src/mvm.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/mvm.c.o
.PHONY : src/mvm.c.o

src/mvm.i: src/mvm.c.i

.PHONY : src/mvm.i

# target to preprocess a source file
src/mvm.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/mvm.c.i
.PHONY : src/mvm.c.i

src/mvm.s: src/mvm.c.s

.PHONY : src/mvm.s

# target to generate assembly for a file
src/mvm.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/mvm.c.s
.PHONY : src/mvm.c.s

src/operators/scan.o: src/operators/scan.c.o

.PHONY : src/operators/scan.o

# target to build an object file
src/operators/scan.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/operators/scan.c.o
.PHONY : src/operators/scan.c.o

src/operators/scan.i: src/operators/scan.c.i

.PHONY : src/operators/scan.i

# target to preprocess a source file
src/operators/scan.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/operators/scan.c.i
.PHONY : src/operators/scan.c.i

src/operators/scan.s: src/operators/scan.c.s

.PHONY : src/operators/scan.s

# target to generate assembly for a file
src/operators/scan.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/operators/scan.c.s
.PHONY : src/operators/scan.c.s

src/pred.o: src/pred.c.o

.PHONY : src/pred.o

# target to build an object file
src/pred.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/pred.c.o
.PHONY : src/pred.c.o

src/pred.i: src/pred.c.i

.PHONY : src/pred.i

# target to preprocess a source file
src/pred.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/pred.c.i
.PHONY : src/pred.c.i

src/pred.s: src/pred.c.s

.PHONY : src/pred.s

# target to generate assembly for a file
src/pred.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/pred.c.s
.PHONY : src/pred.c.s

src/pref.o: src/pref.c.o

.PHONY : src/pref.o

# target to build an object file
src/pref.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/pref.c.o
.PHONY : src/pref.c.o

src/pref.i: src/pref.c.i

.PHONY : src/pref.i

# target to preprocess a source file
src/pref.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/pref.c.i
.PHONY : src/pref.c.i

src/pref.s: src/pref.c.s

.PHONY : src/pref.s

# target to generate assembly for a file
src/pref.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/pref.c.s
.PHONY : src/pref.c.s

src/progpool.o: src/progpool.c.o

.PHONY : src/progpool.o

# target to build an object file
src/progpool.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/progpool.c.o
.PHONY : src/progpool.c.o

src/progpool.i: src/progpool.c.i

.PHONY : src/progpool.i

# target to preprocess a source file
src/progpool.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/progpool.c.i
.PHONY : src/progpool.c.i

src/progpool.s: src/progpool.c.s

.PHONY : src/progpool.s

# target to generate assembly for a file
src/progpool.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/progpool.c.s
.PHONY : src/progpool.c.s

src/schema.o: src/schema.c.o

.PHONY : src/schema.o

# target to build an object file
src/schema.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/schema.c.o
.PHONY : src/schema.c.o

src/schema.i: src/schema.c.i

.PHONY : src/schema.i

# target to preprocess a source file
src/schema.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/schema.c.i
.PHONY : src/schema.c.i

src/schema.s: src/schema.c.s

.PHONY : src/schema.s

# target to generate assembly for a file
src/schema.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/schema.c.s
.PHONY : src/schema.c.s

src/storage/memory.o: src/storage/memory.c.o

.PHONY : src/storage/memory.o

# target to build an object file
src/storage/memory.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/storage/memory.c.o
.PHONY : src/storage/memory.c.o

src/storage/memory.i: src/storage/memory.c.i

.PHONY : src/storage/memory.i

# target to preprocess a source file
src/storage/memory.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/storage/memory.c.i
.PHONY : src/storage/memory.c.i

src/storage/memory.s: src/storage/memory.c.s

.PHONY : src/storage/memory.s

# target to generate assembly for a file
src/storage/memory.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/storage/memory.c.s
.PHONY : src/storage/memory.c.s

src/timer.o: src/timer.c.o

.PHONY : src/timer.o

# target to build an object file
src/timer.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/timer.c.o
.PHONY : src/timer.c.o

src/timer.i: src/timer.c.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/timer.c.i
.PHONY : src/timer.c.i

src/timer.s: src/timer.c.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/timer.c.s
.PHONY : src/timer.c.s

src/tuple.o: src/tuple.c.o

.PHONY : src/tuple.o

# target to build an object file
src/tuple.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuple.c.o
.PHONY : src/tuple.c.o

src/tuple.i: src/tuple.c.i

.PHONY : src/tuple.i

# target to preprocess a source file
src/tuple.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuple.c.i
.PHONY : src/tuple.c.i

src/tuple.s: src/tuple.c.s

.PHONY : src/tuple.s

# target to generate assembly for a file
src/tuple.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuple.c.s
.PHONY : src/tuple.c.s

src/tuple_cursor.o: src/tuple_cursor.c.o

.PHONY : src/tuple_cursor.o

# target to build an object file
src/tuple_cursor.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuple_cursor.c.o
.PHONY : src/tuple_cursor.c.o

src/tuple_cursor.i: src/tuple_cursor.c.i

.PHONY : src/tuple_cursor.i

# target to preprocess a source file
src/tuple_cursor.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuple_cursor.c.i
.PHONY : src/tuple_cursor.c.i

src/tuple_cursor.s: src/tuple_cursor.c.s

.PHONY : src/tuple_cursor.s

# target to generate assembly for a file
src/tuple_cursor.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuple_cursor.c.s
.PHONY : src/tuple_cursor.c.s

src/tuple_field.o: src/tuple_field.c.o

.PHONY : src/tuple_field.o

# target to build an object file
src/tuple_field.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuple_field.c.o
.PHONY : src/tuple_field.c.o

src/tuple_field.i: src/tuple_field.c.i

.PHONY : src/tuple_field.i

# target to preprocess a source file
src/tuple_field.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuple_field.c.i
.PHONY : src/tuple_field.c.i

src/tuple_field.s: src/tuple_field.c.s

.PHONY : src/tuple_field.s

# target to generate assembly for a file
src/tuple_field.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuple_field.c.s
.PHONY : src/tuple_field.c.s

src/tuplet.o: src/tuplet.c.o

.PHONY : src/tuplet.o

# target to build an object file
src/tuplet.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuplet.c.o
.PHONY : src/tuplet.c.o

src/tuplet.i: src/tuplet.c.i

.PHONY : src/tuplet.i

# target to preprocess a source file
src/tuplet.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuplet.c.i
.PHONY : src/tuplet.c.i

src/tuplet.s: src/tuplet.c.s

.PHONY : src/tuplet.s

# target to generate assembly for a file
src/tuplet.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuplet.c.s
.PHONY : src/tuplet.c.s

src/tuplet_field.o: src/tuplet_field.c.o

.PHONY : src/tuplet_field.o

# target to build an object file
src/tuplet_field.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuplet_field.c.o
.PHONY : src/tuplet_field.c.o

src/tuplet_field.i: src/tuplet_field.c.i

.PHONY : src/tuplet_field.i

# target to preprocess a source file
src/tuplet_field.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuplet_field.c.i
.PHONY : src/tuplet_field.c.i

src/tuplet_field.s: src/tuplet_field.c.s

.PHONY : src/tuplet_field.s

# target to generate assembly for a file
src/tuplet_field.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/tuplet_field.c.s
.PHONY : src/tuplet_field.c.s

src/unsafe.o: src/unsafe.c.o

.PHONY : src/unsafe.o

# target to build an object file
src/unsafe.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/unsafe.c.o
.PHONY : src/unsafe.c.o

src/unsafe.i: src/unsafe.c.i

.PHONY : src/unsafe.i

# target to preprocess a source file
src/unsafe.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/unsafe.c.i
.PHONY : src/unsafe.c.i

src/unsafe.s: src/unsafe.c.s

.PHONY : src/unsafe.s

# target to generate assembly for a file
src/unsafe.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/unsafe.c.s
.PHONY : src/unsafe.c.s

src/utils.o: src/utils.c.o

.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/src/utils.c.s
.PHONY : src/utils.c.s

third-party/json-parser/json.o: third-party/json-parser/json.c.o

.PHONY : third-party/json-parser/json.o

# target to build an object file
third-party/json-parser/json.c.o:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/third-party/json-parser/json.c.o
.PHONY : third-party/json-parser/json.c.o

third-party/json-parser/json.i: third-party/json-parser/json.c.i

.PHONY : third-party/json-parser/json.i

# target to preprocess a source file
third-party/json-parser/json.c.i:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/third-party/json-parser/json.c.i
.PHONY : third-party/json-parser/json.c.i

third-party/json-parser/json.s: third-party/json-parser/json.c.s

.PHONY : third-party/json-parser/json.s

# target to generate assembly for a file
third-party/json-parser/json.c.s:
	$(MAKE) -f CMakeFiles/gridstore.dir/build.make CMakeFiles/gridstore.dir/third-party/json-parser/json.c.s
.PHONY : third-party/json-parser/json.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... doc"
	@echo "... gridstore"
	@echo "... gridstore.o"
	@echo "... gridstore.i"
	@echo "... gridstore.s"
	@echo "... src/async.o"
	@echo "... src/async.i"
	@echo "... src/async.s"
	@echo "... src/attr.o"
	@echo "... src/attr.i"
	@echo "... src/attr.s"
	@echo "... src/conf.o"
	@echo "... src/conf.i"
	@echo "... src/conf.s"
	@echo "... src/containers/dict.o"
	@echo "... src/containers/dict.i"
	@echo "... src/containers/dict.s"
	@echo "... src/containers/dicts/hash_table.o"
	@echo "... src/containers/dicts/hash_table.i"
	@echo "... src/containers/dicts/hash_table.s"
	@echo "... src/containers/freelist.o"
	@echo "... src/containers/freelist.i"
	@echo "... src/containers/freelist.s"
	@echo "... src/containers/hashset.o"
	@echo "... src/containers/hashset.i"
	@echo "... src/containers/hashset.s"
	@echo "... src/containers/list.o"
	@echo "... src/containers/list.i"
	@echo "... src/containers/list.s"
	@echo "... src/containers/vec.o"
	@echo "... src/containers/vec.i"
	@echo "... src/containers/vec.s"
	@echo "... src/dispatch.o"
	@echo "... src/dispatch.i"
	@echo "... src/dispatch.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/field_type.o"
	@echo "... src/field_type.i"
	@echo "... src/field_type.s"
	@echo "... src/frag.o"
	@echo "... src/frag.i"
	@echo "... src/frag.s"
	@echo "... src/frag_printer.o"
	@echo "... src/frag_printer.i"
	@echo "... src/frag_printer.s"
	@echo "... src/frag_printers/console_printer.o"
	@echo "... src/frag_printers/console_printer.i"
	@echo "... src/frag_printers/console_printer.s"
	@echo "... src/frags/frag_host_vm.o"
	@echo "... src/frags/frag_host_vm.i"
	@echo "... src/frags/frag_host_vm.s"
	@echo "... src/global.o"
	@echo "... src/global.i"
	@echo "... src/global.s"
	@echo "... src/grid.o"
	@echo "... src/grid.i"
	@echo "... src/grid.s"
	@echo "... src/grid_cursor.o"
	@echo "... src/grid_cursor.i"
	@echo "... src/grid_cursor.s"
	@echo "... src/hash.o"
	@echo "... src/hash.i"
	@echo "... src/hash.s"
	@echo "... src/indexes/hindex.o"
	@echo "... src/indexes/hindex.i"
	@echo "... src/indexes/hindex.s"
	@echo "... src/indexes/hindexes/lsearch_hindex.o"
	@echo "... src/indexes/hindexes/lsearch_hindex.i"
	@echo "... src/indexes/hindexes/lsearch_hindex.s"
	@echo "... src/indexes/vindex.o"
	@echo "... src/indexes/vindex.i"
	@echo "... src/indexes/vindex.s"
	@echo "... src/indexes/vindexes/hash_vindex.o"
	@echo "... src/indexes/vindexes/hash_vindex.i"
	@echo "... src/indexes/vindexes/hash_vindex.s"
	@echo "... src/inet/request.o"
	@echo "... src/inet/request.i"
	@echo "... src/inet/request.s"
	@echo "... src/inet/response.o"
	@echo "... src/inet/response.i"
	@echo "... src/inet/response.s"
	@echo "... src/inet/server.o"
	@echo "... src/inet/server.i"
	@echo "... src/inet/server.s"
	@echo "... src/interval.o"
	@echo "... src/interval.i"
	@echo "... src/interval.s"
	@echo "... src/mondrian.o"
	@echo "... src/mondrian.i"
	@echo "... src/mondrian.s"
	@echo "... src/mvm.o"
	@echo "... src/mvm.i"
	@echo "... src/mvm.s"
	@echo "... src/operators/scan.o"
	@echo "... src/operators/scan.i"
	@echo "... src/operators/scan.s"
	@echo "... src/pred.o"
	@echo "... src/pred.i"
	@echo "... src/pred.s"
	@echo "... src/pref.o"
	@echo "... src/pref.i"
	@echo "... src/pref.s"
	@echo "... src/progpool.o"
	@echo "... src/progpool.i"
	@echo "... src/progpool.s"
	@echo "... src/schema.o"
	@echo "... src/schema.i"
	@echo "... src/schema.s"
	@echo "... src/storage/memory.o"
	@echo "... src/storage/memory.i"
	@echo "... src/storage/memory.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/tuple.o"
	@echo "... src/tuple.i"
	@echo "... src/tuple.s"
	@echo "... src/tuple_cursor.o"
	@echo "... src/tuple_cursor.i"
	@echo "... src/tuple_cursor.s"
	@echo "... src/tuple_field.o"
	@echo "... src/tuple_field.i"
	@echo "... src/tuple_field.s"
	@echo "... src/tuplet.o"
	@echo "... src/tuplet.i"
	@echo "... src/tuplet.s"
	@echo "... src/tuplet_field.o"
	@echo "... src/tuplet_field.i"
	@echo "... src/tuplet_field.s"
	@echo "... src/unsafe.o"
	@echo "... src/unsafe.i"
	@echo "... src/unsafe.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... third-party/json-parser/json.o"
	@echo "... third-party/json-parser/json.i"
	@echo "... third-party/json-parser/json.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

