#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <containers/vector.h>
#include <field.h>
#include <timer.h>

#include "types.h"
#include "tables/customer.h"
#include "tables/lineitem.h"
#include "tables/nation.h"
#include "tables/orders.h"
#include "tables/part.h"
#include "tables/partsupp.h"
#include "tables/region.h"
#include "tables/supplier.h"

static void for_each_line(
        const char *file,
        serialization_config_t *config,
        size_t tuple_str_t_size,
        bool parse(void *capture, void *begin, void *end),
        bool free_parse_result(void *capture, void *begin, void *end),
        size_t tuple_t_size,
        bool convert(void *capture, void *begin, void *end),
        bool free_convert_result(void *capture, void *begin, void *end),
        bool serialize(void *capture, void *begin, void *end));

int main() {

    printf("This is tpch convert. Copyright (c) 2017 Marcus Pinnecke\n"
           "This tools converts the textual database tables as generated by tpch-dbgen into table image files (*timg).\n"
           "A table image file is an easy to use serialization tuplet_format that supports NSM and DSM physical layouts.\n\n"
           "For details on the binary tuplet format, take a look at the source of tpch convert (/utils/tpch-convert/laucher.c)");

    serialization_config_t config = {
        .dest_file = "workloads/olap/tpch/database/customer.timg",
        .format    = TF_DSM
    };

    timer_t timer;
    timer_start(&timer);

    for_each_line("../sbin/tpch-dbgen/customer.tbl",
                  &config,
                  sizeof(tpch_customer_tuple_str_t),
                  parse_customers,
                  free_customer_tuple_str_t,
                  sizeof(tpch_customer_tuple_t),
                  convert_customer_tuple,
                  free_customer_tuple_t,
                  serialize_customer_table);

    timer_stop(&timer);
    printf("\n\ntime taken %0.4fms\n", timer_diff_ms(&timer));

    return EXIT_SUCCESS;
}

static void for_each_line(
        const char *file,
        serialization_config_t *config,
        size_t tuple_str_t_size,
        bool parse(void *capture, void *begin, void *end),
        bool free_parse_result(void *capture, void *begin, void *end),
        size_t tuple_t_size,
        bool convert(void *capture, void *begin, void *end),
        bool free_convert_result(void *capture, void *begin, void *end),
        bool serialize(void *capture, void *begin, void *end))
{
    vector_t *all_lines = vector_create(sizeof(char *), ALL_LINES_VECTOR_INIT_CAP);
    char line[MAX_LINE_LEN];
    FILE *file_ptr = fopen(file, "r");

    while (fgets(line, MAX_LINE_LEN, file_ptr) != NULL) {
        char *line_cpy = strdup(line);
        vector_add(all_lines, 1, &line_cpy);
    }

    fclose(file_ptr);

    vector_t *parse_result = vector_create(tuple_str_t_size, ALL_LINES_VECTOR_INIT_CAP);
    vector_foreach(all_lines, parse_result, parse);
    vector_free__str(all_lines);

    vector_t *convert_result = vector_create(tuple_t_size, ALL_LINES_VECTOR_INIT_CAP);
    vector_foreach(parse_result, convert_result, convert);
    vector_free_ex(parse_result, NULL, free_parse_result);

    vector_foreach(convert_result, config, serialize);
    vector_free_ex(convert_result, NULL, free_convert_result);
}