#pragma once

#define BADARG           "Illegal argument: '%s'"
#define BADCALL          "Illegal call: '%s'"
#define BADMALLOC        "Memory allocation failed: '%s'"
#define BADEXPR          "Bad expression evaluation: '%s'"
#define NOTIMPLEMENTED   "Not implemented: '%s'"
#define BADBRANCH        "Internal error: unknown condition during operation on object %p."
#define BADCAST          "Unsupported cast request for persistent ptr %p."
#define BADTYPE          "Persistent ptr %p points to illegal type."
#define BADBACKLINK      "Internal error: back link for persistent ptr %p is not allowed to be null."
#define BADFRWDLINK      "Internal error: forward link for persistent ptr %p is not allowed to point to a non-zone obj."
#define BADPOOLINIT      "Internal error: page pool %p is already initialized."
#define BADPAGEID        "Internal error: page id '%du' was not loaded into hot store. Maybe it does not exists."
#define BADARGNULL       "Illegal argument for function. Parameter '%s' points to null"
#define BADARGZERO       "Illegal argument for function. Parameter '%s' is zero"
#define UNEXPECTED       "Unexpected behavior: '%s'"
#define BADHURRY         "Not implemented: '%s'"
#define BADPAGESIZE      "Request to create a page size of %zuB with a hot store limit of %zuB is illegal"
#define BADSTATE         "Bad state: %s"
#define BADCOLDSTOREINIT "Memory allocation failed: unable to initialize cold store of buffer manager"
#define BADFREELISTINIT  "Memory allocation failed: unable to initialize page free list in buffer manager"
#define BADHOTSTOREOBJ   "Page with id '%du' is not located in hot store"
#define BADINTERNAL      "Internal error: %s"
#define BADBOUNDS        "Out of bounds access: %s"
#define BADTAG           "Casting error. Object is not instance of required type."
#define BADFRAGTYPE      "Unknown fragment type was requested: %d"